### ISSUE TITLE
Black screen in Ocarina of Time

### ISSUE THREAD

**Issue by Aconcerned** [Jhon591/citra-1#2]
Just checking out the emulator and the log, I found out that Ocarina of Time doesn't work, it renders the sound and you can play, but the screen is black.

This is the log, it seems to be a Kernel issue since the normal Citra doesn't have said error.
https://pastebin.com/TLufWWpe

**Comment by Jhon591** [comment]
sorry did not get you're message, try my newer build
https://ci.appveyor.com/project/Jhno591/citra/build/1.0.82

https://github.com/Jhon591/citra
